version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_HOSTNAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"  # Limit Kafka JVM heap size
    ports:
      - "9093:9093"  # Internal Kafka port
      - "9094:9094"  # External Kafka port
    networks:
      - kafka-net
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 512M

  consumer:
    build:
      context: ./consumer 
    depends_on:
      - kafka
    networks:
      - kafka-net
    deploy:
      resources:
        limits:
          memory: 256M

  producer:
    build:
      context: ./producer 
    depends_on:
      - consumer
    networks:
      - kafka-net
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  kafka-net:
    driver: bridge

